### ISSUE TITLE
issue 2: Checklist page

### ISSUE THREAD

**Issue by stanmoriasi** [jmont2307/meow-rested#7]
As a new employee, I would like to view a checklist page.

**Acceptance Criteria**

- [x] Its done when when there a new checklist page called checklist.html or tracker.html
- [x] Its done when the title of the page reads `New Hire Onboarding Checklist`
- [x] Its done when there is a header on the page that reads `New Hire Onboarding Tracker`
