### ISSUE TITLE
issue 4: Check off task from checklist

### ISSUE THREAD

**Issue by stanmoriasi** [jmont2307/meow-rested#9]
As a new employee, I would like to be able to check off a task from the task list.

**Acceptance Criteria**

- [ ] Its done when I can check off a task from the checklist
- [ ] Its done when there is a strikethrough on the checklist
- [ ] Its done when there is a check mark on the checklist

**Comment by melinanev** [comment]
- OSHA and Safety Building Walkthrough
---Exits
---Fire Extinguishers
---MDS
---Eye Wash Stations
---Break Rooms
---Parking
---Police/Fire Departments
---Security Alarm
- Human Resources/Payroll
---I9 Forms
---W4 Forms 
---Direct Deposit
---Benefits Set Up
---Time Clock
---Scheduling
---Uniform Policy
---OSHA Video Training
---Harassment Video Training
- Technology Set up by Tech Support
---Company Email Set Up 
---Laptop set up 
---Key Card Set Up
- Training
---Meet with manager/supervisor
---Review training materials
---Meet with trainer (if not manager/supervisor)
---Develop Cadence for review
